// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcqlfvED2XKKlhHnOv3olMH0UwPUhG0ao',
    appId: '1:381047757042:web:f39eca3d5723c50a77986b',
    messagingSenderId: '381047757042',
    projectId: 'jikens-auto-garage-aa1ce',
    authDomain: 'jikens-auto-garage-aa1ce.firebaseapp.com',
    storageBucket: 'jikens-auto-garage-aa1ce.firebasestorage.app',
    measurementId: 'G-M6MKQJPQ5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt3qWI3RkgVKQNJg_k_C0St2kCOJH3rrE',
    appId: '1:381047757042:android:bd79ec1eac1a25e177986b',
    messagingSenderId: '381047757042',
    projectId: 'jikens-auto-garage-aa1ce',
    storageBucket: 'jikens-auto-garage-aa1ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCcCIETAdnUmXXUy_6yZS4AREi6Qr6VLc',
    appId: '1:381047757042:ios:64ed579e8b0173e677986b',
    messagingSenderId: '381047757042',
    projectId: 'jikens-auto-garage-aa1ce',
    storageBucket: 'jikens-auto-garage-aa1ce.firebasestorage.app',
    iosBundleId: 'com.example.jikensAutoGarage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCcCIETAdnUmXXUy_6yZS4AREi6Qr6VLc',
    appId: '1:381047757042:ios:64ed579e8b0173e677986b',
    messagingSenderId: '381047757042',
    projectId: 'jikens-auto-garage-aa1ce',
    storageBucket: 'jikens-auto-garage-aa1ce.firebasestorage.app',
    iosBundleId: 'com.example.jikensAutoGarage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcqlfvED2XKKlhHnOv3olMH0UwPUhG0ao',
    appId: '1:381047757042:web:fbb1786b7714ae1a77986b',
    messagingSenderId: '381047757042',
    projectId: 'jikens-auto-garage-aa1ce',
    authDomain: 'jikens-auto-garage-aa1ce.firebaseapp.com',
    storageBucket: 'jikens-auto-garage-aa1ce.firebasestorage.app',
    measurementId: 'G-BTW5QLDLS4',
  );
}
